apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: aerie-scheduler-worker-1
  name: aerie_scheduler_worker_1
spec:
  ports:
    - name: "27189"
      port: 27189
      targetPort: 8080
  selector:
    io.kompose.service: aerie-scheduler-worker-1
