apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: aerie-scheduler
  name: aerie_scheduler
spec:
  ports:
    - name: "27185"
      port: 27185
      targetPort: 27185
  selector:
    io.kompose.service: aerie-scheduler
