apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: aerie-ui
  name: aerie-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: aerie-ui
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: aerie-ui
    spec:
      containers:
        - env:
            - name: ORIGIN
              value: http://localhost
            - name: PUBLIC_AERIE_FILE_STORE_PREFIX
              value: /usr/src/app/merlin_file_store/
            - name: PUBLIC_GATEWAY_CLIENT_URL
              value: http://localhost:9000
            - name: PUBLIC_GATEWAY_SERVER_URL
              value: http://aerie_gateway:9000
            - name: PUBLIC_HASURA_CLIENT_URL
              value: http://localhost:8080/v1/graphql
            - name: PUBLIC_HASURA_SERVER_URL
              value: http://hasura:8080/v1/graphql
            - name: PUBLIC_HASURA_WEB_SOCKET_URL
              value: ws://localhost:8080/v1/graphql
          image: '/aerie-ui:'
          name: aerie-ui
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
