apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: aerie-file-store
  name: aerie-file-store
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
