apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: aerie-merlin-worker-1
  name: aerie_merlin_worker_1
spec:
  ports:
    - name: "27187"
      port: 27187
      targetPort: 8080
  selector:
    io.kompose.service: aerie-merlin-worker-1
