# source: https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  username: bXktYXBw
  password: Mzk1MjgkdmRnN0pi
